Product
Monika-Stokowska/Class-d pull request #6
Opened 2018-05-27 16:10 UTC by Monika-Stokowska

2018-05-27 19:39 UTC, zulixro commented on db/migrate/20180527155058_create_products.rb
> +      t.string :name
Dodaj też walidacje w bazie danych (chyba że ustaliłyście ostatnio, że tego nie robicie). W przeciwnym razie może się zdarzyć, że jakimś sposobem znajdzie się w Twojej bazie danych produkt np. bez nazwy (walidacje w modelach można obejść na różne sposoby).

2018-05-27 19:42 UTC, zulixro requested changes
Great job! Only one suggested change.

2018-05-27 19:42 UTC, zulixro commented on app/models/product.rb
> +end
super

2018-05-27 19:42 UTC, zulixro commented on db/migrate/20180527155058_create_products.rb
> +      t.string :name
Dodaj też walidacje w bazie danych (chyba że ustaliłyście ostatnio, że tego nie robicie). W przeciwnym razie może się zdarzyć, że jakimś sposobem znajdzie się w Twojej bazie danych produkt np. bez nazwy (walidacje w modelach można obejść na różne sposoby).

2018-06-04 17:37 UTC, gpks commented on app/models/product.rb
> +end
indentation though ;D

2018-06-04 17:55 UTC, zulixro approved these changes

2018-06-04 17:57 UTC, merged