WIP - Customer authentication
Monika-Stokowska/Class-d pull request #7
Opened 2018-06-03 12:28 UTC by agrzelewska

Signup doesn/t work, unfortunately. HELP, please! :)

Web browser shows :"Corrupted Content Error" and terminal: 
Started POST "/customers" for 127.0.0.1 at 2018-06-03 14:27:14 +0200
Processing by CustomersController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"IqjzEjN5Bn+deoAlUYyrfcf2w1jgmq7dlmyMvYvL2sw+BT1xtd7NBjjz1CLV8LT8hqFtWgp0PLcHfJ1Nas+I0Q==", "customer"=>{"name"=>"Kate", "email"=>"kate@example.com", "password_digest"=>"[FILTERED]"}, "commit"=>"Sign up"}
Unpermitted parameter: :password_digest
   (1.0ms)  BEGIN
  ↳ app/controllers/customers_controller.rb:8
  Customer Exists (2.3ms)  SELECT  1 AS one FROM "customers" WHERE "customers"."email" = $1 LIMIT $2  [["email", "kate@example.com"], ["LIMIT", 1]]
  ↳ app/controllers/customers_controller.rb:8
   (1.6ms)  ROLLBACK
  ↳ app/controllers/customers_controller.rb:8
Redirected to http://localhost:3000signup
Completed 302 Found in 35ms (ActiveRecord: 4.8ms)

2018-06-03 12:52 UTC, zulixro commented
Look for an error message. In this case it's `Unpermitted parameter: :password_digest`. Try to find out what's going on with that. Hint: look up "permited parameters"

2018-06-03 13:12 UTC, agrzelewska commented
I've seen that. I've tried to find solution but I think that customer_params are correct (when I've changed :password to :password_digest the error was the same)

2018-06-03 13:59 UTC, gpks commented on app/controllers/application_controller.rb
> +		redirect_to '/login' unless current_customer
in ruby we use 2 spaces indentations :)

2018-06-03 14:21 UTC, gpks commented
I checked - if you change `:password` into `:password_digest` in permitted params, as @zulixro wrote, this error is not appearing again, but there is another problem then...

2018-06-03 18:29 UTC, agrzelewska commented
I did it :). I've changed password into password_digest in validation in models/concerns/customers.rb . And now it signs up into db :)

2018-06-03 20:14 UTC, agrzelewska commented
I did some commits - I think it's working now, at least better :)

2018-06-04 07:15 UTC, gpks commented on app/controllers/customers_controller.rb
> +    if @customer.save
please fix indentations here: if you don't know how, I will show you today :)

2018-06-04 07:15 UTC, gpks commented on app/controllers/customers_controller.rb
> +  def show
do we need this method?

2018-06-04 07:15 UTC, gpks commented on app/controllers/customers_controller.rb
> +	  def customer_params
indentations: method should be at the same level as `private`

2018-06-04 07:16 UTC, gpks commented on app/controllers/sessions_controller.rb
> +	if @customer && @customer.authenticate(params[:session][:password])
indentations

2018-06-04 07:16 UTC, gpks commented on app/views/customers/new.html.erb
> +    <%= f.label :name %><br>
👍

2018-06-04 07:17 UTC, gpks commented on app/views/customers/new.html.erb
> +<% end %>
here's why github is showing you this red sign: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2018-06-04 07:20 UTC, gpks requested changes
I have some remarks, but overall: amazing work!!!!! 👏

2018-06-04 17:46 UTC, gpks commented on app/views/customers/show.html.erb
> +dadada
newline please :)

2018-06-04 17:46 UTC, gpks commented on app/views/sessions/new.html.erb
> +<% end %>
newline please

2018-06-04 17:47 UTC, gpks commented on test/models/customer_test.rb
> +  	@customer.name = "    "
indentations 😩

2018-06-04 18:08 UTC, gpks approved these changes

2018-06-04 18:09 UTC, merged